backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "site/static/img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Location, name: location, widget: string}
          - {label: When, name: when, widget: string}
          - {label: "Contact Email", name: contact_email, widget: string}
          - {label: "Buy URL", name: buy_url, widget: string}
          - {label: Program, name: program, widget: "file"}
          - {label: "About Model", name: about, widget: "markdown"}
          - {label: "Join Community URL", name: signUpApi, widget: "string"}
          - {label: "Onboarding text", name: onboarding_text, widget: "string"}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Guests", name: speakers, widget: object, fields: [
              {label: "Name", name: "title", widget: string},
              {label: "Position", name: "subtitle", widget: string},
              {label: "Image", name: "image", widget: "image"},
              {label: "Description", name: "description", widget: "markdown"}]}
          - {label: "Organizations", name: organizations, widget: object, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "URL Website", name: "url", widget: string},
              {label: "Description", name: "description", widget: "markdown"}
              ]}
          - {label: "Organizers", name: logos, widget: object, fields: [
              {label: "Image", name: "url", widget: "image"}]}
          - {label: "Allies", name: allies, widget: object, fields: [
              {label: "Image", name: "image", widget: "image"}]}
          - {label: "Quotes", name: carousel, widget: object, fields: [
              {label: "Image", name: "image", widget: "image"}]}
          - {label: "Prices", name: prices, widget: object, fields: [
              {label: "Description", name: "description", widget: "markdown"},
              {label: "Price", name: "price", widget: "string"}]}
